language: C
notifications:
  irc: "chat.freenode.net#krebs_incoming"
  on_success: change
  on_failure: always
  template:
    - "painload/%{branch} %{commit} %{author}: %{message} %{build_url}"
script: "./test"
branches:
    only:
        - master
